# Matemática Computacional I
- Prof. Felipe C. Minuzzi
- felipe.minuzzi@ufsm.br

## Introdução ao Python

A linguagem de programação `Python` é uma linguagem de alto padrão, orientada a objetos que se mantém de forma colaborativa e aberta. A página oficial é: [https://www.python.org/](https://www.python.org/).

Utilizaremos fortemente o conceito de **notebook**, que permite criar códigos em python, em uma sintaxe combinada com documentação e com visualização direta dos resultados, ou seja, não precisamos nos preocupar com compilação de arquivos do tipo `.py`.

Existem duas principais maneiras de trabalhar com notebooks: o [Jupyter Notebook](https://jupyter.org/) e [Google Colab](https://colab.research.google.com/). Ambos são similares em sua sintaxe, porém o segundo permite um desenvolvimento colaborativo sem a instalação de qualquer programa, ou seja, basta acessar e usar. Já o primeiro requer a instalação dos pacotes do Jupyter e do próprio. Outro motivo que joga a favor do **Colab** é que não precisamos nos preocupar com dependências.

**Para quem quiser baixar localmente o Jupyter Notebook e instalar os pacotes:**
Nesse caso, sugiro seguir esse [tutorial](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter01.01-Getting-Started-with-Python.html) para SO Linux e Mac OS, e [aqui](https://pythonnumericalmethods.berkeley.edu/notebooks/Appendix01-Getting-Started-with-Python-Windows.html#) para Windows. 

## Algumas definições importantes:

Em python, existem os seguintes formatos de números:
 - **Inteiro**: classe int
 - **Não inteiros:** classe float
 - **Complexos:** classe complex
 - **Variáveis não numéricas:** classe string
 - **Booleano:** True ou False (1 ou 0)

Relativo as operadores de comparação, temos:

Operação | Nome | Aplicação | Exemplo | Resposta
--------- | ------ | --------- | --------- |  ---------
> | Maior que | `x > y` | 5 > 4 | True
< | Menor que | `x < y` | 5 < 4 | False
==  | Igual a | `x == y` | 10 == 15 | False
!=  | Diferente de | `x != y` | 10 != 15 | True  
>=  | Maior ou igual a  | `x >= y` | 10 >= 15 | False
<=  | Menor ou igual a  | `x <= y` | 10 <= 10 | True

As operações matemáticas elementares são definidas por:
 - `+` adição  
 - `-` subtração  
 - `*` multiplicação  
 - `/` divisão  
 - `**` potenciação


In [ ]:
5 == 5

True

In [ ]:
4 != 6

True

In [ ]:
6 >= 6

True

In [ ]:
x = 8
y = 6
z = -5

In [ ]:
x + y - z

19

In [ ]:
w = ((x**y) + z**2)/3
print(w)

87389.66666666667


Em python, atribuir um valor a uma variável apenas define aquela variável:

In [14]:
x = -10

In [15]:
print(x**2)

100


Divisão entre números:

In [4]:
7/3

2.3333333333333335

In [5]:
7//3

2

A divisão entre inteiros em Python 3 resulta em um número real (ao contrário de Python 2, onde resulta somente a parte inteira).

In [7]:
3/0

ZeroDivisionError: division by zero

Outro tipo de número que podemos representar é os complexos, onde a unidade imaginária é repreentada por `j`

In [8]:
2 + 3j

(2+3j)

Podemos calcular o módulo desse número complexo:

In [9]:
abs(2+3j)

3.605551275463989

Ou ainda, podemos utilizar a sintaxe `_#cell` para carregar a saída da célula e usá-la em outro lugar:

In [10]:
abs(_9)

3.605551275463989

Note a diferença se utilizarmos `abs` para um número que não é complexo

In [11]:
abs(-6.7)

6.7

E o que acontece se tentarmos comparar números complexos?

In [12]:
1 - 3j > 2 + 1j

TypeError: '>' not supported between instances of 'complex' and 'complex'

A ordem também influencia strings:

In [17]:
'aaab' < 'aaabb'

True

## Trabalhando com listas:

Além dos tipos numéricos e de caracteres, as listas bastante úteis em computação numérica e em python.

As listas são um tipo de variável muito útil no Python. Uma lista pode conter uma série de valores. As variáveis de lista são declaradas usando colchetes [] após o nome da variável.

Por exemplo:

In [21]:
lista = [1,2,3,4,5,6,7,8,9,10]
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [22]:
type(lista)

list

In [23]:
print(len(lista))

10


As listas **não** são vetores no sentido da algebra linear, pois a soma de listas é simplesmente a justaposição. Multiplicar uma lista (ou sequência) por um inteiro é simplesmente repetir a lista esse número de vezes

In [24]:
[1,2,3,4] + ['gato', 'cachorro']

[1, 2, 3, 4, 'gato', 'cachorro']

In [25]:
['maça', 2]*10

['maça',
 2,
 'maça',
 2,
 'maça',
 2,
 'maça',
 2,
 'maça',
 2,
 'maça',
 2,
 'maça',
 2,
 'maça',
 2,
 'maça',
 2,
 'maça',
 2]

In [26]:
exemplo_lista = [1, 2, 3.0, 4 + 0j, "5","abacaxi"]
b = 2*exemplo_lista
c = exemplo_lista*2
print(b)
print(c)

[1, 2, 3.0, (4+0j), '5', 'abacaxi', 1, 2, 3.0, (4+0j), '5', 'abacaxi']
[1, 2, 3.0, (4+0j), '5', 'abacaxi', 1, 2, 3.0, (4+0j), '5', 'abacaxi']


Podemos manipular de diversas maneiras as listas:

In [28]:
#checar se um elemento está em uma lista:
4 in lista

True

In [27]:
#adicionando um elemento a uma lista:
lista.append(78)
print(lista)

In [29]:
#eliminar um elemento da lista:
lista.remove(2)
print(lista)

[1, 3, 4, 5, 6, 7, 8, 9, 10, 78]


In [30]:
#e podemos eliminar dependendo da posição dele na lista:
lista.pop(3) #elimina o elemento da posição 3
print(lista)

[1, 3, 4, 6, 7, 8, 9, 10, 78]


No exemplo acima, o que chama a atenção?

Podemos manipular elementos da lista:

In [32]:
print(lista[0])  # Primeiro elemento, 1
print(lista[1])  # Segundo elemento, 2
print(lista[0:4])  # Desde o primeiro até o  quarto. Aqui Python conta "0,1,2,3" o elemento "4" (que é o quinto da lista) não inclui
print(lista[:3])  # Desde o primero até o terceiro, excluíndo este: 1, 2, 3.0 (similar ao exemplo anterior)
print(lista[-1])  #  último elemento
print(lista[-2])  #  penúltimo elemento
print(lista[:])  # Desde o primeiro até o último
print(lista[::2])  # Desde o primeiro até o último, pulando 2: 1, 3.0

1
3
[1, 3, 4, 6]
[1, 3, 4]
78
10
[1, 3, 4, 6, 7, 8, 9, 10, 78]
[1, 4, 7, 9, 78]


Note que a indexação em python, nativamente, **sempre começa no 0**


## Estruturas de controle de fluxo

### Condicionais:

    if <condition>:
        <do something>
    elif <condition>:
        <do other thing>
    else:
        <do other thing>

**Observação:** Note o espaçamento e a tabulação da sintaxe. Em Python, o `:` delimita o condicional, e tudo que estiver abaixo, dentro de um espaçamento de 4 caracteres, seguirá o fluxo deste condiconal. Voltanto ao espaçamento anterior, "saímos" do condicional.

In [33]:
x = 1
if (x > 10) & (x != 50):
  d = x/6
  print('O quadrado de x é:', x**2)
elif (x > 10) & (x < 100):
  print('O x está entre 10 e 100.')
else:
  print('O x dividido por 10 é:', x/10)

O x dividido por 10 é: 0.1


In [34]:
x = 1
if x < 2:
  print(f'O x é menor que 2 e vale: {x}')
else:
  print(f'O valor de x é {x}')

O x é menor que 2 e vale: 1


Podemos estruturar um condicional usando o booleano:

In [35]:
if 1 > 0:
    print('Sim, 1 é maior que 0')

Sim, 1 é maior que 0


In [38]:
x = 2
y = 9
if x > y:
    print(f'{x} é maior que {y}')

Qual característica do código acima podemos chamar a atenção?

## Estruturas de controle de fluxo

### Repetição:

Em Python existem dois tipos de estruturas de controle de repetição tipicas:

- Loops `while`
- Loops `for`

Os loops `while` repetiram as sentencias anhidadas enquanto se cumpla uma condición:

    while <condition>:
        <things to do>
        
Como no caso dos condicionais, os blocos separam-se por indentação, não havendo  necessidade de sentencias do tipo `end`.

In [39]:
x = -2
while x < 5:
    print(x)
    x = x + 1

-2
-1
0
1
2
3
4


O que acontece se não atualizarmos o valor de `x` no exemplo acima?
Podemos usar também a sintaxe `x += 1` que equivale a `x = x + 1`.

In [40]:
x = -2
while x < 5:
    print(x)
    x += 1

-2
-1
0
1
2
3
4


No caso de não ter  sido previamente interrompido por um `break`, um bloco `else` executa-se justo depois do loop:

In [41]:
x = 0
while x < 5:
    print(x)
    x += 1
    if x == 3:
        break
else:
    print("Loop Terminado")

0
1
2


In [42]:
x = 0
while x < 5:
    print(x)
    x += 1
    #if ii == 3:
        #break
else:
    print("Terminado")

0
1
2
3
4
Terminado


O outro loop indespensável  em Python é `for`, e funciona percorrendo um conjunto definido previamente. 

    for <element> in <iterable_object>:
        <do whatever...>

In [ ]:
for i in range(3,9):
  j = i**2
  print('O valor de i é:', i)
  print('O valor do j é:', j)
  print('Aqui acaba a repetição do bloco')

print('Aqui está fora do código')
y = 6*8
print(y)

O valor de i é: 3
O valor do j é: 9
Aqui acaba a repetição do bloco
O valor de i é: 4
O valor do j é: 16
Aqui acaba a repetição do bloco
O valor de i é: 5
O valor do j é: 25
Aqui acaba a repetição do bloco
O valor de i é: 6
O valor do j é: 36
Aqui acaba a repetição do bloco
O valor de i é: 7
O valor do j é: 49
Aqui acaba a repetição do bloco
O valor de i é: 8
O valor do j é: 64
Aqui acaba a repetição do bloco
Aqui está fora do código
48


In [ ]:
#for i in range(inicio, fim-1, step)

for i in range(2,20,2):
  x = i**2
  print(f'O valor de i é: {i} e o valor de x é: {x}')
#print('Esse é um texto')

O valor de i é: 2 e o valor de x é: 4
O valor de i é: 3 e o valor de x é: 9
O valor de i é: 4 e o valor de x é: 16
O valor de i é: 5 e o valor de x é: 25
O valor de i é: 6 e o valor de x é: 36
O valor de i é: 7 e o valor de x é: 49
O valor de i é: 8 e o valor de x é: 64
O valor de i é: 9 e o valor de x é: 81
O valor de i é: 10 e o valor de x é: 100
O valor de i é: 11 e o valor de x é: 121
O valor de i é: 12 e o valor de x é: 144
O valor de i é: 13 e o valor de x é: 169
O valor de i é: 14 e o valor de x é: 196
O valor de i é: 15 e o valor de x é: 225
O valor de i é: 16 e o valor de x é: 256
O valor de i é: 17 e o valor de x é: 289
O valor de i é: 18 e o valor de x é: 324
O valor de i é: 19 e o valor de x é: 361


In [ ]:
for i in range(10):
  x = i**2
  if i >= 8:
    print(x)
  elif i == 2:
    print('O i é igual a 2.')
  else:
    print(f'O i é menor que 8 e vale {i}')

O i é menor que 8 e vale 0
O i é menor que 8 e vale 1
O i é igual a 2.
O i é menor que 8 e vale 3
O i é menor que 8 e vale 4
O i é menor que 8 e vale 5
O i é menor que 8 e vale 6
O i é menor que 8 e vale 7
64
81


Podemos acessar listas usando o `for`:

In [ ]:
t = [0.1, 0.2, 0.3, 0.4, 0.5]

for elemento in t:
  x = elemento**2
  print(x)

0.010000000000000002
0.04000000000000001
0.09
0.16000000000000003
0.25


In [ ]:
for i in lista[4:8]:
  print(i)

5
6
7
8


In [ ]:
outra_lista = ['Maça','Banana','Melão','Melancia']

for elemento in outra_lista:
  if elemento != 'Maça':
    print(f'A fruta é {elemento}.')

In [ ]:
lista_grande = [[1,2,3], [4,5,6], [7,8,9]]

for a in lista_grande:
  print(a)
  for j in a:
    print(j)

[1, 2, 3]
1
2
3
[4, 5, 6]
4
5
6
[7, 8, 9]
7
8
9


# Importanto bibliotecas

Em python, podemos importar módulos que já possuem funções nativas e que permitem a resolução de alguns tipos de problemas. Uma desses é o ```numpy```, que permite manipular vetores e matrizes, a biblioteca ```math``` que fornece fórmulas matemáticas, ```scipy``` para cálculos científicos, entre inúmeras outras que nos ajudaram na disciplina.

Para importar um módulo em python, usamos a seguinte sintaxe:


```
import (nome da biblioteca)
```
ou, se queremos dar um 'apelido' a essa, podemos usar

```
import (nome da biblioteca) as (apelido)
```

Por exemplo:
```
import numpy as np
import math
```

Abaixo mostramos alguns exemplos do uso dessas bibliotecas


In [ ]:
import math as mt

mt.cos(mt.pi)

-1.0

In [ ]:
import math

x = math.cos(math.pi)
print(x)

z = math.sin(math.pi)
print(z)

k = math.exp(1)
print(k)

h = math.log(math.exp(1))
print(h)

u = math.log10(10)
print(u)

d = math.sqrt(4)
print(d)

-1.0
1.2246467991473532e-16
2.718281828459045
1.0
1.0
2.0


Observe nos exemplos acima que usamos o nome do módulo (nesse caso ```math```), para chamar as funções e comandos específicos. A conexão entre módulo e função se dá por um ponto **( . )**

Sendo assim, o comando


```
math.pi
```
chama o valor de pi para ser utilizado.
Todas funções do módulo podem ser encontradas [nesse link](https://docs.python.org/3/library/math.html?highlight=math#module-math), ou chamando o comando ```help(math)```

Abaixo, traremos alguns exemplos do uso do módulo ```numpy```, ótimo para manipulação de vetores e matrizes. Chamaremos ele através do alias np, o qual é usualmente utilizado. A documentação pode ser encontrada [aqui](https://numpy.org/doc/stable/)


In [ ]:
import numpy as np

#criação de uma matriz 2 x 3
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[-1][-1]

6

In [ ]:
np.shape(A)

(2, 3)

In [ ]:
#criação de uma matriz 4 x 6
B = np.array([[1,2,3,-1,5,6], [0,-1,9,1,5,6],[1,3,-8,-1,0,1],[3,2,0,-1,0,6]])
B

array([[ 1,  2,  3, -1,  5,  6],
       [ 0, -1,  9,  1,  5,  6],
       [ 1,  3, -8, -1,  0,  1],
       [ 3,  2,  0, -1,  0,  6]])

In [ ]:
np.shape(B)

(4, 6)

In [ ]:
vetor = np.array([1,0,1])
vetor

array([1, 0, 1])

In [ ]:
np.shape(vetor)

(3,)

In [ ]:
x = np.linspace(0,1)
y = x.tolist()
print(y)
for i in y:
  if i < 0.1:
    print(i)

[0.0, 0.02040816326530612, 0.04081632653061224, 0.061224489795918366, 0.08163265306122448, 0.1020408163265306, 0.12244897959183673, 0.14285714285714285, 0.16326530612244897, 0.18367346938775508, 0.2040816326530612, 0.22448979591836732, 0.24489795918367346, 0.26530612244897955, 0.2857142857142857, 0.3061224489795918, 0.32653061224489793, 0.3469387755102041, 0.36734693877551017, 0.3877551020408163, 0.4081632653061224, 0.42857142857142855, 0.44897959183673464, 0.4693877551020408, 0.4897959183673469, 0.5102040816326531, 0.5306122448979591, 0.5510204081632653, 0.5714285714285714, 0.5918367346938775, 0.6122448979591836, 0.6326530612244897, 0.6530612244897959, 0.673469387755102, 0.6938775510204082, 0.7142857142857142, 0.7346938775510203, 0.7551020408163265, 0.7755102040816326, 0.7959183673469387, 0.8163265306122448, 0.836734693877551, 0.8571428571428571, 0.8775510204081632, 0.8979591836734693, 0.9183673469387754, 0.9387755102040816, 0.9591836734693877, 0.9795918367346939, 1.0]
0.0
0.020408163

In [ ]:
import math as mt

mt.sqrt(6)

2.449489742783178

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

#sintaxe: np.linspace(inicio do intervalo, fim do intervalo, numero de pontos)
x = np.linspace(-10,10,100)
x

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

In [ ]:
y = x**2
y

array([1.00000000e+02, 9.60004081e+01, 9.20824406e+01, 8.82460973e+01,
       8.44913784e+01, 8.08182838e+01, 7.72268136e+01, 7.37169677e+01,
       7.02887460e+01, 6.69421488e+01, 6.36771758e+01, 6.04938272e+01,
       5.73921028e+01, 5.43720029e+01, 5.14335272e+01, 4.85766758e+01,
       4.58014488e+01, 4.31078461e+01, 4.04958678e+01, 3.79655137e+01,
       3.55167840e+01, 3.31496786e+01, 3.08641975e+01, 2.86603408e+01,
       2.65381084e+01, 2.44975003e+01, 2.25385165e+01, 2.06611570e+01,
       1.88654219e+01, 1.71513111e+01, 1.55188246e+01, 1.39679625e+01,
       1.24987246e+01, 1.11111111e+01, 9.80512193e+00, 8.58075707e+00,
       7.43801653e+00, 6.37690032e+00, 5.39740843e+00, 4.49954086e+00,
       3.68329762e+00, 2.94867871e+00, 2.29568411e+00, 1.72431385e+00,
       1.23456790e+00, 8.26446281e-01, 4.99948985e-01, 2.55076013e-01,
       9.18273646e-02, 1.02030405e-02, 1.02030405e-02, 9.18273646e-02,
       2.55076013e-01, 4.99948985e-01, 8.26446281e-01, 1.23456790e+00,
      