# Matemática Computacional II
- Prof. Felipe C. Minuzzi
- felipe.minuzzi@ufsm.br

## Métodos iterativos para solução de sistemas

Em certos casos, os métodos iterativos são mais indicados do que os métodos diretos (exatos), como por exemplo, quando a matriz dos coeficientes é uma matriz esparsa, isto é, possui muitas entradas nulas. 

Esses métodos ainda necessitam de menos memória para armazenamento e possuem a vantagem de se auto corrigir se um erro é cometido. Além disso, podem ser usados para reduzir os erros de arredondamento na solução obtida por métodos exatos. Podem também, sob certas condições, resolver um conjunto de equações não lineares. Ao usar métodos iterativos, no entanto, precisamos sempre saber se a sequência se soluções aproximadas está convergindo ou não para a solução desejada.

*Teorema:*

A condição necessária e suficiente para a convergência do processo iterativo definido por $x = Hx + g$ é que $max \{ |\lambda_i |\} < 1$, onde $\lambda_i$ são os autovalores da matriz $H$.


Como consequência do teorema acima, o processo será convergente se para qualquer norma de matrizes, $\| H \| < 1$. 

Assim, se $\| H \|<1$ para alguma norma, temos a garantia de que o processo iterativo dado por $ x - x^{(k)} = H(x-x^{(k-1)})$ converge para a solução exata $\bar{x}$. A matriz $H$ é chamada **matriz de iteração**.


## Método iterativo de Jacobi-Richardson

Considere um sistema  de equações lineares $Ax = b$ em que $det(A) \neq 0$, com a diagonal principal $a_{ii} \neq 0$, $i=1,...,n$ como segue

$$ \left\{\begin{array}{l}
	         a_{11}x_1 +a_{12}x_2 + \cdots + a_{1n}x_n = b_1\\
	         a_{21}x_1 +a_{22}x_2 + \cdots + a_{2n}x_n = b_2\\
	         \vdots   \\
	         a_{n1}x_1 +a_{n2}x_2 + \cdots + a_{nn}x_n = b_1\\
\end{array} \right. $$

Dividindo cada linha do sistema dado pelo elemento da diagonal e isolando $x_1$ na $1^a$ equação, $x_2$ na $2^a$ equação até $x_n$ na n-ésima equação, temos o sistema escrito na forma equivalente:

$$ \begin{cases}
	         x_1 = \frac{1}{a_{11}} \left(b_1  - a_{12}x_2 - a_{13}x_3 - \cdots - a_{1n}x_n \right)\\
	         x_2 = \frac{1}{a_{22}} \left(b_2  - a_{21}x_1 - a_{23}x_3 - \cdots - a_{2n}x_n \right)\\
	         \vdots   \\
	         x_n = \frac{1}{a_{nn}} \left(b_n  - a_{n1}x_1 - a_{n2}x_2 - \cdots - a_{n \, n-1}x_{n-1} \right)\\
\end{cases} $$

O método iterativo de Jacobi-Richardson é dado da seguinte forma:

$$ \begin{cases}
             x_1^{(k+1)} = \frac{b_1}{a_{11}}  - \frac{a_{12}}{a_{11}}x_2^{(k)} - \frac{a_{13}}{a_{11}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\
	         x_2^{(k+1)} = \frac{b_2}{a_{22}}  - \frac{a_{21}}{a_{22}}x_1^{(k)} - \frac{a_{23}}{a_{22}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\
	         \vdots   \\
	         x_n^{(k+1)} = \frac{b_n}{a_{nn}}  - \frac{a_{n1}}{a_{nn}}x_1^{(k)} - \frac{a_{n2}}{a_{nn}}x_3^{(k)} - \cdots - \frac{a_{n \, n-1}}{a_{nn}}x_{n-1}^{(k)} \\
\end{cases} $$





### Convergência do método
Se a matriz $A=(a_{ij})_{i,j=1.,,,,n}$ do sistema $Ax=b$ for estritamente diagonal dominante, ou seja,

$$ |a_{ii}| > \sum_{j=1,i\neq j} |a_{ij}| , i=1,...n$$

então, o método iterativo de Jacobi-Richardson será convergente.

### Critério de parada
Considerando que o processo iterativo está fornecendo uma sequência convergente, um critério de parada para o algoritmo pode ser dado por

$$ \frac{\parallel x^n - x^{n-1}\parallel }{\parallel x^n\parallel} < \epsilon$$

para alguma norma vetorial $\parallel . \parallel : V \rightarrow R$ e alguma tolerância $\epsilon$ pré estabelecida.

Por conveniência, é comum utilizarmos a norma infinito:

$$ \parallel x\parallel _ \infty = max \{ |x_0|, |x_1|, ..., |x_n| \}$$

**Exemplo 1:**

Usando o método interativo de Jacobi-Richardson, determine uma solução aproximada para o seguinte sistema de equações lineares, com aproximação inicial $x^{0}=(0,0,0)^t$ e precisão $\epsilon = 0.01$.

$$ \left\{\begin{array}{l}
	         10x_1 + 2x_2 + x_3 = 14\\
	         x_1 + 5x_2 + x_3 = 11\\
	         2x_1 + 3x_2 +10x_3 = 8\\
\end{array} \right. $$

cuja forma matricial é dada por:

$$
\left[\begin{array}{ccc}
10 & 2 & 1\\
1 & 5 & 1\\
2 & 3 & 10\\
\end{array} \right]
\left[\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array} \right]
=
\left[\begin{array}{c}
14\\
11\\
8\\
\end{array} \right]
$$



Reescrevendo o sistema, obtemos:

$$
\begin{cases}
x_1^{(k+1)} = \frac{14}{10} - \frac{2}{10}x_2^{(k)} - \frac{1}{10}x_3^{(k)}\\
x_2^{(k+1)} = \frac{11}{5} - \frac{1}{5}x_1^{(k)} - \frac{1}{5}x_3^{(k)}\\
x_3^{(k+1)} = \frac{8}{10} - \frac{2}{10}x_1^{(k)} - \frac{3}{10}x_2^{(k)}\\
\end{cases}
$$

Em python, podemos fazer como segue

In [2]:
import numpy as np
x = np.array([0.,0.,0.])

def itera(x):
    x1 = 1.4 - 0.2*x[1] - 0.1*x[2]
    x2 = 2.2 - 0.2*x[0] - 0.2*x[2]
    x3 = 0.8 - 0.2*x[0] - 0.3*x[1]
    x = np.array([x1, x2, x3])
    return x

#uma iteração
x = itera(x)
print ("k=1,", "x=",x)

#várias iterações e o erro
x_ant = x
for i in range(1,7):
    x = itera(x)
    err = np.max(abs(x-x_ant))/np.max(abs(x))
    x_ant = x
    print (i, x, err)

k=1, x= [1.4 2.2 0.8]
1 [ 0.88  1.76 -0.14] 0.5340909090909091
2 [1.062 2.052 0.096] 0.1423001949317738
3 [ 0.98    1.9684 -0.028 ] 0.06299532615322088
4 [1.00912 2.0096  0.01348] 0.02064092356687896
5 [ 0.996732  1.99548  -0.004704] 0.009112594463487526
6 [1.0013744 2.0015944 0.0020096] 0.0033541260906805024


Na forma matricial, o podemos escrever o processo iterativo da seguinte maneira,

$$ x^{(k+1)} = Hx^{(k)} + g $$

onde


$$H =
\left[\begin{array}{ccccc}
 0 & -\frac{a_{12}}{a_{11}} & -\frac{a_{13}}{a_{11}} &\cdots & -\frac{a_{1n}}{a_{11}} \\
 -\frac{a_{21}}{a_{22}} & 0 & -\frac{a_{23}}{a_{22}} &\cdots & -\frac{a_{2n}}{a_{22}} \\
  \vdots & \vdots & \vdots & \vdots & \vdots \\
 -\frac{a_{n1}}{a_{nn}} & -\frac{a_{n2}}{a_{nn}} & -\frac{a_{n3}}{a_{nn}}&\cdots & 0 \\
\end{array} \right]
\,\,\,\,\,\,$$
e
$$\,\,\,\,\,\,g =
\left[\begin{array}{c}
\frac{b_1}{a_{11}} \\
\frac{b_2}{a_{22}} \\
\vdots \\
\frac{b_n}{a_{nn}}\\
\end{array} \right]
$$

ou, ainda,


$$
\left[\begin{array}{c}
x_1^{k+1} \\
x_2^{k+1} \\
\vdots \\
x_n^{k+1}\\
\end{array} \right]
=
\left[\begin{array}{ccccc}
 0 & -\frac{a_{12}}{a_{11}} & -\frac{a_{13}}{a_{11}} &\cdots & -\frac{a_{1n}}{a_{11}} \\
 -\frac{a_{21}}{a_{22}} & 0 & -\frac{a_{23}}{a_{22}} &\cdots & -\frac{a_{2n}}{a_{22}} \\
  \vdots & \vdots & \vdots & \vdots & \vdots \\
 -\frac{a_{n1}}{a_{nn}} & -\frac{a_{n2}}{a_{nn}} & -\frac{a_{n3}}{a_{nn}}&\cdots & 0 \\
\end{array} \right]
\left[\begin{array}{c}
x_1^{k} \\
x_2^{k} \\
\vdots \\
x_n^{k}\\
\end{array} \right]
+
\left[\begin{array}{c}
\frac{b_1}{a_{11}} \\
\frac{b_2}{a_{22}} \\
\vdots \\
\frac{b_n}{a_{nn}}\\
\end{array} \right]
$$

**Exemplo 2:**

Resolva o sistema

$$ \left\{\begin{array}{l}
	         x_1 + 0.5x_2 = 1 \\
	         0.5x_1 - x_2 = -1\\
\end{array} \right. $$

In [ ]:
# vamos criar uma abordagem diferente para resolver o sistema
(x1,x2) = (0,0)

f = lambda x1,x2: (1-0.5*x2, 1+0.5*x1)

for i in range(10):
    (x1,x2) = f(x1, x2)
    print (x1,x2)

1.0 1.0
0.5 1.5
0.25 1.25
0.375 1.125
0.4375 1.1875
0.40625 1.21875
0.390625 1.203125
0.3984375 1.1953125
0.40234375 1.19921875
0.400390625 1.201171875


**Exemplo 3:**

Vamos resolver o sistema do exemplo 1 usando a abordagem do exemplo 2:

In [ ]:
x = [0,0,0]

x1 = lambda x2, x3: 1.4 - 0.2*x2 - 0.1*x3
x2 = lambda x1, x3: 2.2 - 0.2*x1 - 0.2*x3
x3 = lambda x1, x2: 0.8 - 0.2*x1 - 0.3*x2

for k in range(20):
     x = [x1(x[1],x[2]), x2(x[0],x[2]), x3(x[0],x[1])]
     print ("(%.4f,"%x[0],"%.4f,"%x[1],"%.4f)"%x[2])

(1.4000, 2.2000, 0.8000)
(0.8800, 1.7600, -0.1400)
(1.0620, 2.0520, 0.0960)
(0.9800, 1.9684, -0.0280)
(1.0091, 2.0096, 0.0135)
(0.9967, 1.9955, -0.0047)
(1.0014, 2.0016, 0.0020)
(0.9995, 1.9993, -0.0008)
(1.0002, 2.0003, 0.0003)
(0.9999, 1.9999, -0.0001)
(1.0000, 2.0000, 0.0000)
(1.0000, 2.0000, -0.0000)
(1.0000, 2.0000, 0.0000)
(1.0000, 2.0000, -0.0000)
(1.0000, 2.0000, 0.0000)
(1.0000, 2.0000, -0.0000)
(1.0000, 2.0000, 0.0000)
(1.0000, 2.0000, -0.0000)
(1.0000, 2.0000, 0.0000)
(1.0000, 2.0000, -0.0000)


Podemos criar um código que resolva o sistema, via método de Jacobi-Richardson, pela fórmula matricial. Isso facilita se formos criar uma função em python para generalizar nossa solução.

In [6]:
#criando a matriz e o vetor dos termos independentes
A = np.array([[10.0, 2.0, 1.0],
              [ 1.0, 5.0, 1.0],
              [ 2.0, 3.0, 10.0]])
b = np.array([14., 11., 8.])

#chute inicial
x = np.array([0,0,0])
x_ant = x.copy()

#criando a matriz H e o vetor g
n = len(A)
H = A.copy()
g = b.copy()

err = 10.0
for i in range(n):
    H[i] = -A[i]/A[i][i]
    g[i] = b[i]/A[i,i]

H = H + np.identity(3) #zerando os elementos da diagonal
print(H)
print("Norma inf de H=", np.linalg.norm(H, np.inf))
print(50*'*')

while err>0.001:
    x = np.dot(H,x)+g
    err = abs(max(x-x_ant)/max(x))
    x_ant = x
    
print(f'A solução é:')
print(f'x1 = {x[0]}')
print(f'x2 = {x[1]}')
print(f'x3 = {x[2]}')

[[ 0.  -0.2 -0.1]
 [-0.2  0.  -0.2]
 [-0.2 -0.3  0. ]]
Norma inf de H= 0.5
**************************************************
A solução é:
x1 = 0.9994801599999998
x2 = 1.9993232000000003
x3 = -0.0007531999999998984


## Método iterativo de Gaus-Seidel

Considere um sistema  de equações lineares $Ax = b$ em que $det(A) \neq 0$, com a diagonal principal $a_{ii} \neq 0$, $i=1,...,n$ como segue

$$ \left\{\begin{array}{l}
	         a_{11}x_1 +a_{12}x_2 + \cdots + a_{1n}x_n = b_1\\
	         a_{21}x_1 +a_{22}x_2 + \cdots + a_{2n}x_n = b_2\\
	         \vdots   \\
	         a_{n1}x_1 +a_{n2}x_2 + \cdots + a_{nn}x_n = b_1\\
\end{array} \right. $$

Dividindo cada linha do sistema dado pelo elemento da diagonal e isolando $x_1$ na $1^a$ equação, $x_2$ na $2^a$ equação até $x_n$ na n-ésima equação, temos o sistema escrito na forma equivalente:

$$ \begin{cases}
	         x_1 = \frac{1}{a_{11}} \left(b_1  - a_{12}x_2 - a_{13}x_3 - \cdots - a_{1n}x_n \right)\\
	         x_2 = \frac{1}{a_{22}} \left(b_2  - a_{21}x_1 - a_{23}x_3 - \cdots - a_{2n}x_n \right)\\
	         \vdots   \\
	         x_n = \frac{1}{a_{nn}} \left(b_n  - a_{n1}x_1 - a_{n2}x_2 - \cdots - a_{n \, n-1}x_{n-1} \right)\\
\end{cases} $$

O método iterativo de Gauss-Seidel é dado da seguinte forma:

$$ \begin{cases}
             x_1^{(k+1)} = \frac{b_1}{a_{11}}  - \frac{a_{12}}{a_{11}}x_2^{(k)} - \frac{a_{13}}{a_{11}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\
	         x_2^{(k+1)} = \frac{b_2}{a_{22}}  - \frac{a_{21}}{a_{22}}x_1^{(k+1)} - \frac{a_{23}}{a_{22}}x_3^{(k)} - \cdots - \frac{a_{1n}}{a_{11}}x_n^{(k)} \\
	         \vdots   \\
	         x_n^{(k+1)} = \frac{b_n}{a_{nn}}  - \frac{a_{n1}}{a_{nn}}x_1^{(k+1)} - \frac{a_{n2}}{a_{nn}}x_3^{(k+1)} - \cdots - \frac{a_{n \, n-1}}{a_{nn}}x_{n-1}^{(k+1)} \\
\end{cases} $$


**Exemplo 3**

Resolva o sistema:

$$ \left\{\begin{array}{l}
	         -10x_1 + 2x_2 + 2x_3 = -8\\
	         x_1 + 6x_2  = 7\\
	         -x_1 + x_2 + 3x_3 = 0\\
\end{array} \right. $$

In [ ]:
#definindo A e b

A = np.array([[-10., 2.0, 2.0],
              [ 1.0, 6.0, 0.0],
              [-1.0, 1.0, 3.0]])
b = np.array([-8., 7., 0.])

x     = np.array([0.,0.,0.])
x_ant = x.copy()
eps   = 0.0001

x1 = lambda x2, x3: (b[0] - A[0,1]*x2 - A[0,2]*x3)/A[0,0]
x2 = lambda x1, x3: (b[1] - A[1,0]*x1 - A[1,2]*x3)/A[1,1]
x3 = lambda x1, x2: (b[2] - A[2,0]*x1 - A[2,1]*x2)/A[2,2]

err = 10.
while err > eps:
    x[0] = x1(x[1],x[2])
    x[1] = x2(x[0],x[2])
    x[2] = x3(x[0],x[1])
    
    err = np.amax(np.absolute(x-x_ant))/np.amax(np.absolute(x))
    print ("(%.4f,"%x[0],"%.4f,"%x[1],"%.4f)"%x[2], "err=",err)
    x_ant = np.copy(x)

[[-10.   2.   2.]
 [  1.   6.   0.]
 [ -1.   1.   3.]]
[-8.  7.  0.]


**Exemplo 4**

Resolva o sistema do exemplo 1, agora usando o método de Gauss-Seidel

In [ ]:
#definindo A e b
A = np.array([[10,2,1],
              [1,5,1],
              [2,3,10]])
b = np.array([14,11,8])

x = np.array([0.,0.,0.])
x_ant = np.array([0.,0.,0.])
eps = 0.01

x1 = lambda x2, x3: (b[0] - A[0,1]*x2 - A[0,2]*x3)/A[0,0]
x2 = lambda x1, x3: (b[1] - A[1,0]*x1 - A[1,2]*x3)/A[1,1]
x3 = lambda x1, x2: (b[2] - A[2,0]*x1 - A[2,1]*x2)/A[2,2]

err = 10.
while err>eps:

    x[0] = x1(x[1],x[2])
    x[1] = x2(x[0],x[2])
    x[2] = x3(x[0],x[1])
    
    err = np.amax(np.absolute(x-x_ant))/np.amax(np.absolute(x))
    print("(%.4f,"%x[0],"%.4f,"%x[1],"%.4f)"%x[2], "err=",err)
    x_ant = np.copy(x)

[[10  2  1]
 [ 1  5  1]
 [ 2  3 10]]
[14 11  8]


**Exemplo 5**

Resolva o sistema:

$$ \left\{\begin{array}{l}
	         5x_1 + x_2 + 2x_3 + x_4 - x_5 = 1\\
	         6x_2 + x_3 + x_4 - x_5 = 2\\
	         x_2 -3x_3 + 2x_4 + x_5 = 0\\
             3x_1 + 2x_3 + 7x_4 = 2\\
             x_1 + x_2 + 8x_5 = 1\\
\end{array} \right. $$

In [ ]:
A = np.array([[5,1,2,1,-1],
              [0,6,1,1,-1],
              [0,1,-3,2,1],
              [3,0,2,7,0],
              [1,1,0,0,8]])
b = np.array([1,2,0,2,1])

x = np.array([0.,0.,0.,0,0])
x_ant = np.array([0.,0.,0.,0,0])
eps = 0.0001

x1 = lambda x2, x3, x4, x5: (b[0] - A[0,1]*x2 - A[0,2]*x3 - A[0,3]*x4 - A[0,4]*x5)/A[0,0]
x2 = lambda x1, x3, x4, x5: (b[1] - A[1,0]*x1 - A[1,2]*x3 - A[1,3]*x4 - A[1,4]*x5)/A[1,1]
x3 = lambda x1, x2, x4, x5: (b[2] - A[2,0]*x1 - A[2,1]*x2 - A[2,3]*x4 - A[2,4]*x5)/A[2,2]
x4 = lambda x1, x2, x3, x5: (b[3] - A[3,0]*x1 - A[3,1]*x2 - A[3,2]*x3 - A[3,4]*x5)/A[3,3]
x5 = lambda x1, x2, x3, x4: (b[4] - A[4,0]*x1 - A[4,1]*x2 - A[4,2]*x3 - A[4,3]*x4)/A[4,4]

err = 10.
while err>eps:
    x[0] = x1(x[1],x[2],x[3],x[4])
    x[1] = x2(x[0],x[2],x[3],x[4])
    x[2] = x3(x[0],x[1],x[3],x[4])
    x[3] = x4(x[0],x[1],x[2],x[4])
    x[4] = x5(x[0],x[1],x[2],x[3])
    
    err = np.amax(np.absolute(x-x_ant))/np.amax(np.absolute(x))
    print ("(%.4f,"%x[0],"%.4f,"%x[1],"%.4f,"%x[2],"%.4f,"%x[3],"%.4f,)"%x[4], "err=",err)
    x_ant = np.copy(x)

[[ 5  1  2  1 -1]
 [ 0  6  1  1 -1]
 [ 0  1 -3  2  1]
 [ 3  0  2  7  0]
 [ 1  1  0  0  8]]
[1 2 0 2 1]


Na forma matricial, o método de Gauss-Seidel  pode ser escrito como

$$\left[
    \begin{array}{c}
	         x_1^{(k+1)} \\
	         x_2^{(k+1)} \\
             \vdots\\
	         x_n^{(k+1)} \\
	\end{array}
\right]
=
\left[\begin{array}{ccccc}
	         0                     & 0 & 0 & \cdots & 0 \\
	         -\frac{a_{21}}{a_{22}} & 0 & 0 & \cdots & 0 \\
	         \vdots & \vdots & \vdots & \vdots & \vdots \\
	         -\frac{a_{n1}}{a_{nn}} & -\frac{a_{n2}}{a_{nn}} & \cdots & -\frac{a_{n \,n-1}}{a_{nn}} & 0\\
	         \end{array} \right]
             \left[
    \begin{array}{c}
	         x_1^{(k+1)} \\
	         x_2^{(k+1)} \\
             \vdots\\
	         x_n^{(k+1)} \\
	\end{array}
\right]
+
\left[\begin{array}{ccccc}
	         0&  -\frac{a_{12}}{a_{11}}& -\frac{a_{13}}{a_{11}}& \cdots &-\frac{a_{1n}}{a_{11}} \\
	         0& 0& -\frac{a_{23}}{a_{22}} & \cdots & -\frac{a_{2n}}{a_{22}} \\
	         \vdots & \vdots & \vdots & \vdots & \vdots \\
	         0& 0& 0& \cdots& 0\\
	         \end{array} \right]
\left[\begin{array}{c}
	         x_1^{(k)} \\
	         x_2^{(k)} \\
             \vdots\\
	         x_n^{(k)} \\
	\end{array} \right]
+
\left[ \begin{array}{c}
	         \frac{b_1}{a_{11}} \\
	         \frac{b_2}{a_{22}} \\
             \vdots\\
	         \frac{b_n}{a_{nn}} \\
	\end{array} \right]$$


ou
$$ x^{(k+1)} = P x^{(k+1)} + Q x^{(k)} + g$$

$$ (I-P)x^{(k+1)} = Q x^{(k)} + g$$

$$ x^{(k+1)} = (I-P)^{-1}Q x^{(k)} + (I-P)^{-1}g$$

Fazendo-se $H = (I-P)^{-1}Q$ e $g' =(I-P)^{-1}g$ o processo iterativo torna-se

$$x^{(k+1)} = H x^{(k)} + g'$$

Agora usando operações vetoriais com Numpy

In [8]:
x = np.array([0.,0.,0.,0,0])
x_ant = x.copy()
eps = 0.001

A = np.array([[5,1,2,1,-1],
              [0,6,1,1,-1],
              [0,1,-3,2,1],
              [3,0,2,7,0],
              [1,1,0,0,8]])
b = np.array([1,2,0,2,1])

n = len(A)
err = 10.
while err > eps:
    for i in range(n):
        x[i] = (b[i] - np.dot(A[i,0:i],x[0:i])-np.dot(A[i,i+1:n],x[i+1:n]))/A[i,i]
    err = np.amax(np.absolute(x-x_ant))/np.amax(np.absolute(x))

    print ("(%.4f,"%x[0],"%.4f,"%x[1],"%.4f,"%x[2],"%.4f,"%x[3],"%.4f,)"%x[4], "err=",err)
    x_ant = np.copy(x)

print(f'Resultado final: {np.round(x,4)}')

(0.2000, 0.3333, 0.1111, 0.1683, 0.0583,) err= 1.0
(0.0669, 0.2965, 0.2304, 0.1912, 0.0796,) err= 0.4488958286861477
(0.0262, 0.2763, 0.2461, 0.2042, 0.0872,) err= 0.14731623998678248
(0.0229, 0.2728, 0.2561, 0.2027, 0.0880,) err= 0.03672029746344947
(0.0201, 0.2715, 0.2550, 0.2043, 0.0886,) err= 0.010484703792705614
(0.0205, 0.2715, 0.2562, 0.2037, 0.0885,) err= 0.004427429100359636
(0.0202, 0.2714, 0.2558, 0.2040, 0.0886,) err= 0.0015913196833544697
(0.0203, 0.2715, 0.2560, 0.2039, 0.0885,) err= 0.0008282016028654157
Resultado final: [0.0203 0.2715 0.256  0.2039 0.0885]


**Atividade 3**

Baseado nos códigos que vimos acima, crie uma função que receba a matriz dos coeficientes A e o vetor dos termos independentes b e retorne a solução do sistema via:
- método de Jacobi-Richardison
- método de Gauss-Seidel

obs.: a melhor maneira de fazer isso é pelo algoritmo matricial.

Após, resolva o sistema abaixo pelos métodos de Jacobi e Gauss-Seidel:

$$\left\{
\begin{array}{l}
x_1+10x_2+3x_3=27\\
4x_1+x_3=6\\
2x_1+x_2+4x_3=12
\end{array}
\right.$$

**Atividade 4**

Considere o problema de 5 incógnitas e cinco equações dado por

$$\left\{
\begin{array}{r}
x_1-x_2&=&1\\
-x_{1}+2x_2-x_{3}&=&1\\
-x_{2}+(2+\varepsilon) x_3-x_{4}&=&1\\
-x_{3}+2x_4-x_{5}&=&1\\
x_{4}-x_{5}&=&1
\end{array}
\right.$$

- a) Escreva na forma $Ax=b$ e resolva usando eliminação gaussiana para $\varepsilon=10^{-3}$.
- b) Obtenha o vetor incógnita $x$ com $\varepsilon=10^{-3}$ usando Jacobi com tolerância $10^{-2}$. 
- c) Obtenha o vetor incógnita $x$ com $\varepsilon=10^{-3}$ usando Gauss-Seidel com tolerância $10^{-2}$.
- d) Compare os três resultados.
